# pullPolicy defaults to IfNotPresent. The containers will only be pulled
# if they don't already exist on the parent node.
blog:
   imageName: blog.mvc
   imageTag: latest
   pullPolicy: Never

ingress: NodePort