apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: sql-server
spec:
  selector:
    matchLabels:
      app: sql-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sql-server
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: microsoft/mssql-server-linux
        name: sql-server
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: SA_PASSWORD
          valueFrom:
              secretKeyRef:
                name: sql-server-pass
                key: sa_password
        ports:
        - containerPort: 1433
          name: sql-server
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data